### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by mmmmar** [Jorgen-VikingGod/ESP8266-MFRC522#10]
your code is just working fine, but after It works for some time later, It can't read card's uid.
I have no idea about this, any help coulde be fine. 
Thanks.

**Comment by Jorgen-VikingGod** [comment]
@mmmmar this is just an example of using RFID on ESP8266. I'm also just using the [RFID library of Miguel Balboa](https://github.com/miguelbalboa/rfid)

Please make an issue there, if something not working in the lib itself...
