### ISSUE TITLE
Wiring image RST is wrong

### ISSUE THREAD

**Issue by iAbadia** [Jorgen-VikingGod/ESP8266-MFRC522#11]
Wiring image shows RST pin must be wired to GPIO15, that pin can't be used for RST.

**Comment by Jorgen-VikingGod** [comment]
that is not right. It can, but not on every ESP module - they are really different in quality.
My first board - I was creating the example worked perfect and stable. Other modules are really unstable.
I deleted the wiring image, because of unstable and old wiring.
