### ISSUE TITLE
licensing and updating

### ISSUE THREAD

**Issue by beyondszine** [Jorgen-VikingGod/ESP8266-MFRC522#12]
Hi @Jorgen-VikingGod 
I am using your library for certain modifications and then will try to merge them in a seperate branch at miguelbalboa 's library.
 How to do that with taking care of your contributions all along?
Kindly ignore me for my lack of knowledge in terms of licensing and stuff.
I am developing at 
https://github.com/beyondszine/rfid/tree/master
on ESP8266 branch.

**Comment by Jorgen-VikingGod** [comment]
hi @beyondszine don't worry about modifications, because this repo is just an simple example of using the lib with ESP8266. 
If you have some changes/fixes done in your fork - maybe it is a good idea to make a pull request to miguelbalboa's repo.

**Comment by beyondszine** [comment]
yeah, I did one pull for that in the main arduino library, now I am trying to replicate all the examples that he did for Arduino, for ESP8266 in  a seperate branch.
