### ISSUE TITLE
extension possible?

### ISSUE THREAD

**Issue by dodekaeder** [Jorgen-VikingGod/ESP8266-MFRC522#2]
Hey,
technically i'm a noob. So here my noobie question:

Is this setup easily extendable with an electric strike? 

If it would be possible to extend this with a relay-something (e.g. an electric strike http://bit.ly/1NkDxGf ),
i would like to write some door-access app.

**Comment by chinmoyrick** [comment]
You can do it . this esp module have some gpio pin that can be configure as switch of your door locker . but in those sketch is different from this sketch .

**Comment by Jorgen-VikingGod** [comment]
This sketch only shows how to use RFID on ESP8266 and I do not want to add other dependencies to this sketch. But you are free to fork and add what you want to your branch
