### ISSUE TITLE
error: espcomm_open failed

### ISSUE THREAD

**Issue by devishj** [Jorgen-VikingGod/ESP8266-MFRC522#4]
Please help me with this error.
I have done the same wiring connections as given. 
But it is giving the error.
error: espcomm_open failed

And which board should I use?

**Comment by devishj** [comment]
And please tell me connections with esp8266-01 module?

**Comment by chinmoyrick** [comment]
esp 01 module have 8 pin only ,there is two pin for rx and tx for upload program and two pin gpio 0,gpio2 and vcc ,chpd,rst gnd--you can upload program with TTL cp2102 

those type error come true when you error connection Connect it properly ..

take a TTL 
ESP--------------TTL
vcc------------other power supply 3.3v
gnd ---------- TTL gnd
RX---------------TXD
TX---------------RXD
CHPD----------3.3v of TTL
RST ---------RST of TTL or left it high 3.3v
Gpio15-----------Gnd   
GPIO 0------------DTR

connect it and don't

**Comment by devishj** [comment]
Can I use Arduino uno instead of TTL cp2102.
If possible, then what are the connections with it?

**Comment by devishj** [comment]
@chinmoyrick : Can you please be clear with the wiring connections.
Please specify complete wiring connections of MFRC522 with ESP8266 E 12 or with ESP9266 01 and with Arduino Uno

**Comment by chinmoyrick** [comment]
Is it not a clear for you ?
I also work with this project ,

at first you connect esp module with TTL device (connected as like my picture)
then try with basic blink project .try to get a successful upload.
then try with next one..

**Comment by devishj** [comment]
Can I use Arduino Uno instead of TTL device?

**Comment by chinmoyrick** [comment]
I don't know how
There is some problem with board selection (select esp12e from board selection)
but you can test it .
connect as like as TTL connection

gpio 0 ---HIGH--- 3.3v
gpio 15-- low--- gnd

**Comment by devishj** [comment]
@chinmoyrick Please can v a skype chat. Its urgent. I dont have time. Please please help.

**Comment by chinmoyrick** [comment]
It also take time ,understanding project.if you connect properly It must be work.you have to configure your arduino IDE . Board management . I can show you but it also take some time. I don't have option to skype chat with you at present time .

1> what is your operational  work done in this type project.
2> all kind of esp board showing same error.
3> do you test it, with my picture operation
4> what do you wandering        

witch kind of help you actually want from me. don't miss-understand. fill free.....

**Comment by Jorgen-VikingGod** [comment]
Sorry - but this is not an issue of this sketch. It is your environment (power supply and flashing of ESP8266)
If you follow the guidelines of how to flash and connect ESP8266 - everything should work (in case you have a working ESP8266 ;) )
So I decide to close this issue here - because it is out of topic.
