### ISSUE TITLE
RST problem

### ISSUE THREAD

**Issue by skorokithakis** [Jorgen-VikingGod/ESP8266-MFRC522#5]
I'd just like to remark here that connecting the RST to GPIO15, as instructed, doesn't work for me. The ESP8266 doesn't even boot. Leaving RST unconnected seems to work fine, although I'm not sure what I'm missing.

**Comment by devishj** [comment]
@skorokithakis Can you please send me your circuit diagram and all the steps of connection. I need it urgently.

**Comment by devishj** [comment]
@skorokithakis Also please send me the running code. I have an urgent project and I have got only 1 day to complete it.

**Comment by chinmoyrick** [comment]
hi
connect  gpio 15 pin with ground <gen ground pin> and check your sketch ..
RST connected with RST pin <reset program >

**Comment by skorokithakis** [comment]
Leaving GPIO15 unconnected on a NodeMCU works fine. The RST on the ESP12 is an input, so connecting that to the RST pin of the reader wouldn't work, since that's also an input, no?

I'll change the GPIO pin in the code and report back, thanks.

**Comment by skorokithakis** [comment]
That worked, thank you! Looks like the GPIO15 on a NodeMCU isn't meant to be connected anywhere. Looks like it's used as TXD2, whatever that means.
