### ISSUE TITLE
Your configuration causes continue reboot

### ISSUE THREAD

**Issue by asetyde** [Jorgen-VikingGod/ESP8266-MFRC522#6]
i must use gpio5 for rst and gpio4 for sad , other configuration fail

**Comment by Jorgen-VikingGod** [comment]
Don't know why it should fail and forces reboots.
What type of ESP8266 did you use?
I testes several pins and they worked fine for me.

On my last project (using ESP-12E), I switch to following pins:
```
MISO - GPIO12 (hw spi)
MOSI - GPIO13 (hw spi)
SCK  - GPIO14 (hw spi)
SS   - GPIO04 (free GPIO)
RST  - GPIO16 (free GPIO)
```

**Comment by chinmoyrick** [comment]
yes i think you are right .. in my attendance system
RST pin -- D1 == GPIO 5

**Comment by msdorachua** [comment]
Hi,

Just want to say thanks for all the tips here, especially the one from asetyde.

I was using a Wemos D1 board (http://www.wemos.cc/Products/d1.html) using GPIO9 for RST and GPIO 10 for SDA and could not get it to work for such a long time, though the same wiring worked on my non-WIFI enabled Arduino UNO board.

After switching to GPIO5 and GPIO4, the thing worked perfectly! :)

Really appreciate the help! :)
