### ISSUE TITLE
Working sample on ESP-12e

### ISSUE THREAD

**Issue by svrooij** [Jorgen-VikingGod/ESP8266-MFRC522#7]
Thanks for your sample, with some digging I found a working config for the ESP-12E, here is the diagram.

I only switched the pins in the code.
```
#define RST_PIN  2 // RST-PIN für RC522 - RFID - SPI - Modul GPIO15 
#define SS_PIN  15  // SDA-PIN für RC522 - RFID - SPI - Modul GPIO2 
``` 
![esp-12e_rc522](https://cloud.githubusercontent.com/assets/1292510/19768078/2becd3e8-9c56-11e6-8a4f-d6acc25a045e.png)

**Comment by Jorgen-VikingGod** [comment]
thx for the hint.
I will close this issue and use it to update my sketch...

I now changed my example sketch to RST=GPIO5 and SS=GPIO4
this is the working pin layout for the most boards
