### ISSUE TITLE
MFRC522 not scanning card with Wemos D1 Mini

### ISSUE THREAD

**Issue by geramayank** [Jorgen-VikingGod/ESP8266-MFRC522#8]
I have configured the Pins as per Readme and also tired RST with D8, D2 but nothing works. Running DumpInfo Example. I checked the connections again since earlier they were loose and i got a response form 	mfrc522.PCD_DumpVersionToSerial(); return firmware version v2. I am stuck here with this,  any suggestions or the sensor is broken :) ?

Thanks

**Comment by chinmoyrick** [comment]
jorgen sir plz don't mind ..

change pin no in your sketch ..
rst = d1 ----- pin 2 
ss  = d4 ------pin 5
my problem solved this way ..try.
