### ISSUE TITLE
Is it possible to change wiring scheme for MOSI and MISO?

### ISSUE THREAD

**Issue by ceremcem** [Jorgen-VikingGod/ESP8266-MFRC522#9]
I couldn't find how to change wiring layout. Library requires connecting 

```
MOSI -> GPIO13
MISO -> GPIO12
```

I was using another firmware and many PCB's are built while connecting 

```
MOSI -> GPIO12
MISO -> GPIO13
```

Is there any way to initialize MFRC object by defining `MOSI` and `MISO` pins appropriately for my case?

**Comment by Jorgen-VikingGod** [comment]
@ceremcem maybe you have to force issue on the maintainer of the library.
It uses the hardware SPI pins - if you want to use other pins (like SW SPI) - the library have to be changed...
This repository is just an simple example of how to use it by ESP8266.

**Comment by ceremcem** [comment]
Right, thank you. Anyone else can find it [here](https://github.com/miguelbalboa/rfid/issues/295)
